### ISSUE TITLE
The content in GrayIm and in raw laserscanner data with the same image number doesn't match

### ISSUE THREAD

**Issue by tin1254** [EmaroLab/PDT#1]
I read and convert the laserscanner data and from txt and compare it with the Graylm.
Starting from GrayIm, the image contents in the laserscanner data and Graylm don't match starting from scan 131
![Screenshot from 2020-05-26 00-33-50](https://user-images.githubusercontent.com/22342030/82846417-111e7a00-9ee9-11ea-94e3-c0a920af70a1.png)
![Screenshot from 2020-05-26 00-34-17](https://user-images.githubusercontent.com/22342030/82846419-12e83d80-9ee9-11ea-9ace-e21801da20d8.png)

**Comment by tin1254** [comment]
Another question is how you generate the Graylm with the coordinates from laserscanner?
I found the scalings of data from laserscanner vs Graylm are different
![Screenshot from 2020-05-26 00-41-37](https://user-images.githubusercontent.com/22342030/82846577-d5d07b00-9ee9-11ea-8c40-850a3efed500.png)

In the screenshot, the scaling of x-axis is clearly different by looking at the pallet

**Comment by IhabMohamed** [comment]
Hi @tin1254 

sorry for the delayed response. Right now, I do not have a Matlab installed in my machine to check. However, as you know, we have [340 scans](https://github.com/EmaroLab/PDT/tree/master/Pallet_Detection/AllData/Class1)  that have been converted into [340 images](https://github.com/EmaroLab/PDT/blob/master/Pallet_Detection/AllData/PalletImages/RGBImages.tar.gz), which after that resized into 250x250 pixels. Afterward, these images are rotated by 90 and -90 degrees. Moreover, please, consider the RGB images given [here](https://github.com/EmaroLab/PDT/blob/master/Pallet_Detection/AllData/PalletImages/RGBImages.tar.gz) (especially, **Pallet250size** folder), because I do not remember whether we updated the ROI for Gray images or not. Also, the table of images and their ROI generated by the `Image Labeler App` might not have the same order as your original data. Here is an example: inside **RGBImages.tar.gz** `/PalletRGBImages/Pallet250size/PalletDataWithRotation_RGBImage_NoOverlaps.mat` 

Converting the raw data given by the laser scanner from Polar to Cartesian coordinates is given [here](https://github.com/EmaroLab/PDT/blob/master/Pallet_Detection/XYLaserScan.m).

I hope that helps a little bit!

**Comment by IhabMohamed** [comment]
Hi @tin1254

Could you please close this issue if we answered your question?

Regards,

**Comment by tin1254** [comment]
@IhabMohamed Thanks for the answer. However, I still can't find solution to the correspondence between the ROI and the raw laser scanner data, as I would like to use the sensor data.
My observation of this issue was based on `AllData/PalletImages/PalletGrayImages.zip`, there is a file named `GrayPalletDataset.mat`, which I believe contains the ROI of the gray images.
I think the order was just somehow permuted by `Image Labeler App`

**Comment by IhabMohamed** [comment]
@tin1254, as I told you, we have used the RGB images. I think their order might be permuted as well. So, if you are interested in the ROIs of the raw data, it might be easier to generate them using `Image Labeler App`.
